pipeline:
  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - docker_password
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+egar
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/egar-python-3
    tags:
      - build-${DRONE_BUILD_NUMBER}
    when:
      branch:
        exclude: master
      event: [ push, pull_request ]

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - docker_password
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+egar
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/egar-python-3
    tags:
      - latest
    when:
      branch: master
      event: [ push ]

  tagged_image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - docker_password
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+egar
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/egar-python-3
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
