---
kind: pipeline
name: default
type: kubernetes


platform:
  os: linux
  arch: amd64


steps:
# - name: Build
#   pull: if-not-exists
#   image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind:latest
#   commands:
#   # Wait for the docker service to be up
#   - echo "Checking for docker availability."
#   - n=0; while [ "$n" -lt 60 ] && ! docker stats --no-stream >/dev/null 2>&1; do n=$(( n + 1 )); sleep 1; done
#   - echo "echo docker now available."
#   - docker build -t egar-python3.9:$${DRONE_COMMIT} .
#   volumes:
#   - name: dockersock
#     path: /var/run


# - name: Push image to artifactory
#   pull: if-not-exists
#   image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind:latest
#   commands:
#   # Wait for the docker service to be up
#   - echo "Checking for docker availability."
#   - n=0; while [ "$n" -lt 60 ] && ! docker stats --no-stream >/dev/null 2>&1; do n=$(( n + 1 )); sleep 1; done
#   - echo "echo docker now available."
#   - docker login -u="$${DOCKER_USERNAME}" -p="$${DOCKER_PASSWORD}" docker.digital.homeoffice.gov.uk
#   - docker tag egar-python3.9:$${DRONE_COMMIT} docker.digital.homeoffice.gov.uk/egar/egar-python3.9:$${DRONE_COMMIT}
#   - docker push docker.digital.homeoffice.gov.uk/egar/egar-python3.9:$${DRONE_COMMIT}
#   environment:
#     DOCKER_PASSWORD:
#       from_secret: DOCKER_PASSWORD
#     DOCKER_USERNAME:
#       from_secret: DOCKER_USERNAME
#   when:
#     branch:
#     - master
#     - feature/*
#     event:
#     - push
- name: build_new_image_push_to_quay
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind:latest
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME: ukhomeofficedigital+egar
    DOCKER_REGISTRY_URL: quay.io
    IMAGE_NAME: quay.io/ukhomeofficedigital/egar-python3.9
  when:
    branch:
    - master
    - feature/*
    event:
    - push

# trigger to push new build
  commands:
  # Wait for the docker service to be up
  - echo "Checking for docker availability."
  - n=0; while [ "$n" -lt 60 ] && ! docker stats --no-stream >/dev/null 2>&1; do n=$(( n + 1 )); sleep 1; done
  - echo "echo docker now available."
  - docker login -u="$${DOCKER_USERNAME}" -p="$${DOCKER_PASSWORD}" quay.io
  - docker build -t egar-python3.9:$${DRONE_COMMIT} .
  - docker tag egar-python3.9:$${DRONE_COMMIT} $${DOCKER_REGISTRY_URL}/ukhomeofficedigital/egar-python3.9:latest
  - docker push $${DOCKER_REGISTRY_URL}/ukhomeofficedigital/egar-python3.9:latest
  volumes:
    - name: dockersock
      path: /var/run
  settings:
    group: build-stage

- name: scan-image
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
  failure: ignore
  resources:
    limits:
      cpu: 1000
      memory: 1024Mi
  environment:
    IMAGE_NAME: quay.io/ukhomeofficedigital/egar-python3.9:${DRONE_COMMIT}
    IGNORE_UNFIXED: true
  when:
    event:
    - push
    depends_on: build_new_image_push_to_quay

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

volumes:
  - name: dockersock
    temp: {}
